### PR TITLE
feat: Cookbook Onboard (AI Assistant & Playground) integration

### LINKED ISSUE #35: Feature Proposal: Cookbook Onboard (AI Assistant & Playground)
Preview link: https://movement-labs-cookbook-onboard.vercel.app/

## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Movement Labs resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Movement Labs, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity and Move language coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Movement-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

image

## Cookbook Onboard Playground
The Cookbook Onboard Playground embeds a Solidity IDE with smart contract templates displayed alongside the Ask Cookbook AI Assistant.

Developers can search for and deploy Cookbook’s entire smart contract library from your technical documentation.

Features:
- Deploy smart contracts or entire protocols to Movement without leaving Movement Lab's technical docs
- Acts as a free, no-code or low-code token and NFT launchpad
- Save source code as a Foundry, Hardhat, or Scaffold project or export it to Remix or Chain IDE in one click

image

### PR DESCRIPTION
**Pull request by ClockRide**
Resolves #35

### CODE REVIEW

**Comment by Rahat-ch** [comment]
hi @ClockRide thanks for this pr - noticed that cookbook returns outdated information whats the best way to ensure its updated?

**Comment by ClockRide** [comment]
> hi @ClockRide thanks for this pr - noticed that cookbook returns outdated information whats the best way to ensure its updated?

We have a CMS website where you can configure or reindex data sources used for the Movement Labs docs, as well as refine bot replies by leaving feedback on its previous conversations. Could you please send me your email address in Telegram chat we have with your team already, so I can send you an access link to the CMS?

**Comment by ClockRide** [comment]
@Rahat-ch are there any other questions or concerns we can address to get this merged? :)

**Comment by Rahat-ch** [comment]
Hey @ClockRide want to see if we can get this merged in now - would you be able to pull in latest for merge conflict resolution?

**Comment by ClockRide** [comment]
> Hey @ClockRide want to see if we can get this merged in now - would you be able to pull in latest for merge conflict resolution?

Rebased onto the master :)

**Review by Rahat-ch — APPROVED** [review]

**Pull request merged**
