### PR TITLE
feat: wallet adapter contents

### PR DESCRIPTION
**Pull request by jayden-dang**
- dapp builders
- useWallet() functions describe
- Browser extension wallets
- SDK wallet builders
- Move-VM Wallet Standard

### CODE REVIEW

**Comment by Rahat-ch** [comment]
@jayden-dang sent some comments on slack

**Review by Rahat-ch — CHANGES_REQUESTED** [review]
Looking good @jayden-dang last thing would be to update the _category_.json implementation. 

take a look at how these files are structured 

Screenshot 2024-12-10 at 10 04 20 AM

We are no longer using generated index and will use the index.mdx file with the custom card list to render everything

**Comment by jayden-dang** [comment]
@Rahat-ch i done it, can you check it again

**Comment by Rahat-ch** [comment]
I think also after thinking it through @jayden-dang the important parts are the builder and useWallet sections we can talk more about adding the rest at a later date if needed

**Review by Rahat-ch — APPROVED** [review]

**Pull request merged**
